auto: true
server: false
server_port: 4000
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
paginate: 10
rdiscount:
  extensions: [smart, generate_toc]
  toc_token: "{:toc}"